server:
  port: 5001

spring:
  application:
    name: ms-product

  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_cloud2021_product?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://localhost:1002/eureka

secret:
  key: ms-secret-key

mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.spacetim.ms.product.pojo


# Actuator端点暴露
management:
  endpoints:
    web:
      exposure:
        # 配置Actuator暴露那些端点  ②
        include: '*'
database:
  center:
    id: 1001
